fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.12.0"
  repositories:
    "apt": "git://github.com/puppetlabs/puppetlabs-apt.git"
    "staging": "git://github.com/voxpupuli/puppet-staging.git"
    "erlang:": "git://github.com/garethr/garethr-erlang.git"
  symlinks:
    "rabbitmq": "#{source_dir}"
